### ISSUE TITLE
Cannot use TreatWarningsAsErrors=true in WebSharper projects

### ISSUE THREAD

**Issue by nightroman** [dotnet-websharper/core#1031]
Steps to reproduce:

(1) install WebSharper.Templates

    dotnet new -i WebSharper.Templates

(2) in a new project directory create a WebSharper project

    dotnet new websharper-lib -lang f#

(3) build

    dotnet build

Notice warnings

    FSC : parse warning FS3186: An error occurred while reading the F# metadata
    node at position 1 in table 'itycons' of assembly 'WebSharper.Core.JavaScript,
    Version=4 .5.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node
    had no matching declaration. Please report this warning. You may need to
    recompile the F# assembly you are using.

(4) disable warning in fsproj

      <PropertyGroup>
        <NoWarn>FS3186</NoWarn>
      </PropertyGroup>

The build is "clean" now.

(5) Enable TreatWarningsAsErrors in fsproj

      <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <WebSharperProject>Library</WebSharperProject>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      </PropertyGroup>

and build

    dotnet build
    
**Expected result**

wsfsc works and build succeeds.

**Actual result**

wsfsc fails without clear error messages, just this is printed:

    C:\Program Files\dotnet\sdk\2.1.403\FSharp\Microsoft.FSharp.Targets(265,9):
    error MSB6006: "wsfsc.cmd" exited with code 1.

**Comment by nightroman** [comment]
Any updates on this? Workarounds, thoughts?

We have a large solution where in 1/2 of projects we cannot enforce "warnings as errors" due to this issue. As a result, warnings occasionally go through successful local builds to the main repository and make noise (difficult to see de facto errors at times). It's inconvenient.

**Comment by granicz** [comment]
You are right, I just confirmed this. Let see if we can get this into the next release.

**Comment by Jand42** [comment]
@nightroman Thanks for the detailed report. It is now released in [4.5.4.317](https://github.com/dotnet-websharper/core/releases/tag/4.5.4.317).

Problem was that F#+WS compilation uses FSharp.Compiler.Services in 2 ways: first to build a dll and second to get the checker results for JS compilation. At the latter, WS was assuming if there is any errors, the former has printed it already. But it turns out that checker results do not handle NoWarn automatically, so I had to explicitly exclude errors that are turning up in checker results only because it is affected by TreatWarningsAsErrors but not NoWarn. Current fix is safe without an FCS change. (There is a ticket for that too https://github.com/fsharp/FSharp.Compiler.Service/issues/790)

**Comment by remmah** [comment]
Hello! I created a new WS-web project (`dotnet new websharper-web -lang f#`) using version 4.5.6.320, and the FS3186 warning comes up when building:

```
FSC : parse warning FS3186: An error occurred while reading the F# metadata node 
at position 1 in table 'itycons' of assembly 'WebSharper.Core.JavaScript, Version=4.5.0.0, 
Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration.
Please report this warning. You may need to recompile the F# assembly you are using.
```

Based on the discussion above, it was unclear to me if these warnings should still be showing up or not — wanted to report just in case.

**Comment by Jand42** [comment]
@remmah Hi, this is a known issue, warnings added by FSharp.Compiler.Service version 25.0.1. A new version was just released, I will test updating to it and also modify warning filtering rules so these are hidden if this is still happening.
