### ISSUE TITLE
"You must provide assembly output path" error on netcore sdk 2.1.600+

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1053]
Trying to compile netcore templates with sdk version 2.1.600 or later results in
`FSC : WebSharper error FS9001: You must provide assembly output path.`

Workaround: set sdk version by adding a `global.json`

```json
{
  "sdk": {
    "version": "2.1.100"
  }
}
```

(or other version, up to `2.1.505`)

**Comment by ajuch** [comment]
I'm currently affected by this issue too. Until a week ago I had no problems building with the docker dotnet sdk 2.2. I'm puzzled how my build can break since I'm having my websharper dependencies frozen because of #1044. The only thing I can imagine is that a newer minor version of the 2.2 sdk docker image was accidentially pulled, but that is in contradiction to your statement that all versions up to 2.1.505 are faulty...

Can you help me understand that?

**Comment by Jand42** [comment]
@ajuch Sorry, took me some time to realize that the arguments temp file that was passed in was not loaded correctly because newer FSharp.Build also passes the path to fsc.exe as the first argument. Have a small fix that works, releasing it with a newer FCS included that might hopefully resolve other build issues with later netcore.

**Comment by Jand42** [comment]
@ajuch Fix released in https://github.com/dotnet-websharper/core/releases/tag/4.5.11.334

**Comment by ajuch** [comment]
Thank you, the fix works!

**Comment by Gastove** [comment]
Hello! Just to keep everyone on their toes: I'm hitting this now. I'm on a newer version than the one listed in the patch above: `WebSharper - 4.5.16.344`. And: the same fix described by the OP is working for me, albeit with a 2.2 SDK version:

```json
// Global.json
{
    "sdk": {
        "version": "2.2.401"
    }
}
```
Can anyone provide any guidance? What other information can I provide?
