### ISSUE TITLE
match inside List not working

### ISSUE THREAD

**Issue by ajuch** [dotnet-websharper/core#1066]
I have a problem with match statements inside of lists. I expect
`[match true with true -> true |false -> false]` to be equal `[true]`.

On the .net side this is the case, but inside WebSharper translated JavaScript this statement results in `[]`.

**Comment by Tarmil** [comment]
I think this is because WebSharper hasn't been updated to F# 4.7 yet, which added implicit yield.

`if` or `match` directly in a list turns it into a `yield`-based sequence expression, so here you have a `match` that yields either `true` or `false` in F# 4.7, but doesn't yield anything in F# 4.6. If you want it to be a "normal" list, you need to parenthesize the `match`:

```fsharp
[(match true with true -> true | false -> false)]
```

**Comment by ajuch** [comment]
Thank you, the parantheses work! I wasn't aware that this feature was introduced lately in F#...

**Comment by granicz** [comment]
FYI, updating to F# 4.7 is pending on #1064 , once that's in we'll bump the minor version and release.

**Comment by Jand42** [comment]
@ajuch Hi, new F# syntax and functions are now supported in https://github.com/dotnet-websharper/core/releases/tag/4.5.19.349
