### ISSUE TITLE
Add ES6 module import helpers

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1114]
New functions `JS.Import`, `JS.ImportDefault`, `JS.ImportAll`. Recommended usage:

```fsharp
[<Inline>]
let importTestJsAll : obj = JS.ImportAll "/modules/test.js"
// translates to: import * as test from "/modules/test.js"

[<Inline>]
let importTestJs : obj = JS.Import("testExport", "/modules/test.js")
// translates to: import { testExport } from "/modules/test.js"

[<Inline>]
let importTestJsDefault : obj = JS.ImportDefault "/modules/test.js"
// translates to: import def$test from "/modules/test.js"
```

**Comment by giuliohome** [comment]
As per my comment on the gitter channel I see 2 issues here:

1. the import statement is not accepted without the module tag in the script, but this is autogenerated from W# so it must be fixed there I believe...
2. also if I manually skip the above blocking issue (by saving the index and the auto generated script from chrome dev tools and by [changing the tag there](https://github.com/giuliohome/WS.React.DatePicker/blob/master/SPA/indexSaved.html#L33)), the vanilla javascript import cannot find the react export (afaik because the names are changed since the dist script is compiled by node with webpack ), hence we need a sort of "jsx import" for ws react?

See my

**Comment by Jand42** [comment]
Tested with webpack, `Runtime.js` causes an error, not setting global value in a safe way. Wrapping in function and using `self` as global object (instead of `window` for webworker compatibility).

**Comment by Jand42** [comment]
@giuliohome Released in https://github.com/dotnet-websharper/core/releases/tag/4.7.0.423
WS output is not following proper module scoping rules yet, still exporting to global object, but they should work as modules. Sitelets projects now automatically mark as `type=module` any link that has external `import`s from using helpers above.
