### ISSUE TITLE
WIG Pattern.EnumInlines won't work with pattern matching

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/core#1121]
I'm not sure if this is an 4.7 issue yet, but I've started testing WebSocket and found a problem with WIG `Pattern.EnumInlines`. Specifically, [this one](https://github.com/dotnet-websharper/core/blob/fc52ac762838935c3e59bf79388d590abfca08fc/src/stdlib/WebSharper.JavaScript/Html5.fs#L2616).

The problem happens when I try to use it with pattern matching.

```fsharp
match socket.Connection.ReadyState with
| Connecting ->
    Console.Log("ReadyState:Connecting")

| Open ->
    Console.Log("ReadyState:Open")

| Closing ->
    Console.Log("ReadyState:Closing")

| Closed ->
    Console.Log("ReadyState:Closed")
```

For instance, when `socket.Connection.ReadyState` value is 1 (Open), it prints the _Connecting message_.

While prefixing each case with `WebSocketReadyState` (like `WebSocketReadyState.Connecting -> ...`), the compiler issues the following message:

```fsharp
F# Compiler: The type 'WebSocketReadyState' does not define the field, constructor or member 'Connecting'.
```

I've created a [sample project](https://github.com/AlexPeret/websharper-tests/tree/master/WebSharperWebSocketChat) to test it. Uncomment the `//ERROR block` at [ChatPage.fs file](https://github.com/AlexPeret/websharper-tests/blob/80489f353f435987d982ad63fff2bfc347660ef2/WebSharperWebSocketChat/ChatPage.fs#L68) to find the issue.

Thanks,
Alex

Copying @jand42 as per Adam's request.

**Comment by Jand42** [comment]
@AlexPeret Hi! Thanks for the sample! This is caused by a limitation of WIG: it creates a dll by writing IL directly with System.Reflection.Emit, but no F# metadata (FSharpOptimizationData/FSharpSignatureData resource files) are created. So it currently does not support creating proper F# union or record types, active patterns and so on, anything F#-specific.
`Pattern.EnumInlines` is creating a class with static getters, with WebSharper `Inline` attributes. So these values can be used as a property accessor, but F# does not support pattern matching against them. F# can match against constant values (but those can't be any type, just literal types), and active patterns (which require F# metadata to define).

As a workaround, you can create the active pattern yourself, which uses simple comparisons against the static properties created by WIG:

```fsharp
    let (|Connecting|Open|Closing|Closed|) readyState =
        if readyState = WebSocketReadyState.Connecting then Connecting
        elif readyState = WebSocketReadyState.Open then Open
        elif readyState = WebSocketReadyState.Closing then Closing
        else Closed
```

Then matching with `| Connecting ->` will work as expected. Was not working for you above because `Connecting` was unrecognized and so F# compiler interpreted it as a pattern matching target variable (you should see a warning "Uppercase variable identifiers should not generally be used in patterns, and may indicate a missing open declaration or a misspelt pattern name." in this case, F# compiler warns like this against possible unintended matching variables)

I am looking into adding active patterns for "enums" defined by WebSharper.Javascript inside WebSharper.Main (in namespace WebSharper.JavaScript), so above would be available by default. I need to test that it does not break anything existing.

**Comment by AlexPeret** [comment]
@Jand42 Thanks for the detailed answer and the workaround. I noticed the property and field values from Intellisense, but it didn't click to me.

I'll make note of this comment as I'm planning to write about WIG soon.
