### ISSUE TITLE
osx-x64 support missing for wsfscservice

### ISSUE THREAD

**Issue by Jand42** [dotnet-websharper/core#1217]
Platform-specific compiler builds added in #1184 are missing osx-x64. Causes error: `/tools/net5.0/osx-x64//wsfsc.sh: No such file or directory`

No known workarounds

**Comment by mrtank** [comment]
There is no such RID for osx to support websharper:

https://github.com/dotnet-websharper/core/blob/1593e1045e49ae23836e3573659a551718deb8ef/build.fsx#L75

Only linux support has been tested.
Things to consider:
* What does osx use for background services (nohup and & works?)
* opt for `zsh` instead of bash (again is nohup supported?)
* does osx support NamedPipes?
* does osx support global mutex?
