### ISSUE TITLE
Failed to translate property access: patternInput, for tuple

### ISSUE THREAD

**Issue by fjoppe** [dotnet-websharper/core#346]
In a [&lt;Javascript&gt;] section, this perfect F# fails to compile in a Websharper project (v3.0.15.92-alpha):

let (a,b) = (1, "2")

A workaround is:
let tmp = (1, "2")
let a= fst(tmp)
let b = snd(tmp)

Note that in my real-world app, instead of using a hard-coded tuple like (1, "2"), this value was returned from a function.

The workaround above becomes cumbersome for this situation, this will lead to even more extra code:
let (a,b,c,d,e) = (4,"6",8,"10",12)

**Comment by Tarmil** [comment]
This is unfortunately a problem in the F# compiler, which does not generate a reflected definition for the tuple but only for the components (it generates code equivalent to your hand unrolling, but the `let tmp ...` is not reflected). I [reported it](http://fslang.uservoice.com/forums/245727-f-language/suggestions/6475447-enhance-reflecteddefinition-for-pattern-matched-le) some time ago and the issue is up for grabs, I haven't taken the time to dive into the F# compiler source code to fix it yet though.

**Comment by fjoppe** [comment]
Ok, I'll have to live with it for now, thanks for your answer.

**Comment by Tarmil** [comment]
This is not a problem anymore in WebSharper 4.
