### ISSUE TITLE
Server-side template with `ws-replace="styles"` breaks client

### ISSUE THREAD

**Issue by stevehv** [dotnet-websharper/core#898]
Yesterday I tried creating my first app with WebSharper. After much confusion why none of my client side code would work, I found out that the culprit was the line `<style ws-replace="styles"></style>`. For some reason adding this line (which described in the documentation part "Special holes in server-side templates" in https://developers.websharper.com/docs/v4.1/fs/ui) breaks the app so that none of the client-side Javascript or Docs appear on the website. However, there are no error messages in the console or anything else which would indicate that there would be a problem, the app just breaks silently for no apparent reason.

You can easily reproduce this problem by creating a new project in Visual Studio with the `WebSharper 4 Client-Server Application` or the `Websharper 4 Suave-hosted Site` template, then adding the line `<style ws-replace="styles"></style>` at the end of the `head` block in `Main.html`. Once you do that and open the site, you'll see that none of the client-side parts load.

As a side note: there also seems to also be a copy-paste error in the relevant part of the docs (it says scripts where it should probably say styles)
> styles is replaced with the CSS files required by the client-side code included in the page. Usage: <script ws-replace="scripts"></script>

**Comment by granicz** [comment]
Yes, I just confirmed this, unfortunately. The quick workaround is not to use a separate placeholder for `styles` for the time being. Will see about getting this fixed ASAP, thanks for the report!

**Comment by granicz** [comment]
(The fix will be in [UI](https://github.com/dotnet-websharper/ui), by the way.)

**Comment by Tarmil** [comment]
Okay, just to make it clear what's going on. Out of the three special holes `scripts`, `styles` and `meta`, which ones do you have in your template? If I understand correctly, you have `scripts` and `styles` but not `meta`.

When you only have `scripts`, then the contents of `styles` and `meta` are automatically added next to it. But if you also have one of `styles` and `meta` then the other one is not added automatically, which is probably why you are seeing this breakage: you are missing the generated `<meta>` tag.

We should definitely improve this, so that if there's only one of `styles` and `meta` then the other one should be added next to it. Until then, you can work around it by adding a `<meta ws-replace="meta" />` next to your `styles` hole.

**Comment by Tarmil** [comment]
Also, thanks for pointing out the documentation issue! I'm fixing it right now.

**Comment by granicz** [comment]
You are right, I missed this entirely and spoke too soon. Given the above, the current behavior is justified, but it's likely that others will fall into the same trap. Treating a single `styles` or `meta` as a combination of the two is the best solution I can think of as well, perhaps with a warning generated from the UI templating type provider to flag it.

**Comment by stevehv** [comment]
@Tarmil Your explanation is indeed correct, the problem is fixed by also defining the meta tag. The suggested improvement would reduce the potential for confusion. Thanks for picking this up.

**Comment by Tarmil** [comment]
This has been fixed in WebSharper.UI 4.2.1.86, see dotnet-websharper/ui#152.
